name: tests

on: [push, pull_request]

jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        include:
          - python-version: 2.7
            os: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install tox
    - name: Test with tox
      run: |
        PY=py$(echo ${{ matrix.python-version }} | tr -d ".")
        tox -e ${PY}
